 /* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.systenenregistre;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;    
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import javax.swing.JFileChooser;
/**
 *
 * @author PC
 */
public class fenetre1 extends javax.swing.JFrame {

    /**
     * Creates new form fenetre1
     */
    public fenetre1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ilgili Alini Secin");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Kaydet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenuItem1.setText("Adress Ekle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Area Temizle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ad");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Soyad");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefon");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0 ### - ### - ## - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Durum");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ogrenci");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Calisiyor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(17, 17, 17))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Kan Grupu");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jCheckBox1.setText("A");

        jCheckBox2.setText("B");

        jCheckBox3.setText("AB");

        jCheckBox4.setText("O");

        buttonGroup2.add(jCheckBox5);
        jCheckBox5.setText("Rh+");

        buttonGroup2.add(jCheckBox6);
        jCheckBox6.setText("Rh-");

        jLabel10.setText("Resu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addGap(12, 12, 12)
                .addComponent(jCheckBox6)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButton1.setText("Ilgi Alani Sec");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Adress");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Il");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ilce");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenu1.setText("Dosya");

        jMenuItem3.setText("Ac");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Kaydet");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem10.setText("Kaydet_info");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem5.setText("Cikis");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem7.setText("New file");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("New Projet");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Projet Open");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFrame1.setSize(300, 350);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            FileReader fr=new FileReader("C:\\Users\\PC\\Desktop\\github1\\Java-Semestre2\\SystenEnregistre\\src\\main\\java\\com\\mycompany\\systenenregistre/konfigurasyon.txt");
            BufferedReader br=new BufferedReader(fr);
            iller = new String[81];
            ilkodlari = new Vector<>(); 
            ilmodel = new DefaultComboBoxModel();
            ilceler = new DefaultComboBoxModel[81];
            ilgi = new DefaultListModel();
            String line = br.readLine();
            while(line!=null){
                String[] parcala = line.split("//");
                switch(parcala[0])
                {
                    case "il":
                        iller[Integer.valueOf(parcala[1])]=parcala[2];
                        break;
                    case "ilce":
                        if (ilceler[Integer.valueOf(parcala[1])] == null)
                            ilceler[Integer.valueOf(parcala[1])] = new DefaultComboBoxModel();
                        ilceler[Integer.valueOf(parcala[1])].addElement(parcala[2]);
                        break;
                    case "ilgi":
                         ilgi.addElement(parcala[1]);
                         break;  
                }  
                line = br.readLine();
            }
            br.close();
            //ilkodlari.clear();
            for (int i = 0; i < 81; i++) {
                if(iller[i] != null) {
                    ilmodel.addElement(iller[i]);
                    ilkodlari.add(i);
                }             
            }

            jComboBox1.setModel(ilmodel);
            
            int secilikod = ilkodlari.get(jComboBox1.getSelectedIndex());
            jComboBox2.setModel(ilceler[secilikod]);
            
            jList1.setModel(ilgi);
            
            jTextArea1.setComponentPopupMenu(jPopupMenu1);
        }
        catch (IOException ee)
                {
                     JOptionPane.showMessageDialog(null, "Dosya bulunamadı", "Hata", JOptionPane.ERROR_MESSAGE);
                }
        catch (NumberFormatException  ee)
                {
                     JOptionPane.showMessageDialog(null, "Dosya formatını kontrol edin", "Hata", JOptionPane.ERROR_MESSAGE);
                }
        finally{}
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int secilikod=ilkodlari.get(jComboBox1.getSelectedIndex()); 
        jComboBox2.setModel(ilceler[secilikod]);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTextArea1.append(jComboBox1.getSelectedItem()+" / "+jComboBox2.getSelectedItem()+"\n");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        kaydet();
        
        String fileName = "Donnees.xlsx";
        File file = new File(fileName);
        Workbook workbook;
        Sheet sheet;
        
        try {
            if (file.exists()) {
                // Ouvrir le fichier existant
                FileInputStream fis = new FileInputStream(file);
                workbook = new XSSFWorkbook(fis);
                fis.close(); // fermer l'entrée
                sheet = workbook.getSheetAt(0);   //récupérer la première feuille (ou onglet) du fichier Excel ouvert. car on peut avoir plusieurs feuilles   ////  int nbFeuilles = workbook.getNumberOfSheets();
            } else {
                // Créer un nouveau fichier
                workbook = new XSSFWorkbook();
                sheet = workbook.createSheet("Feuille 1");
            }
            // Écrire une ligne
        Row row = sheet.createRow(0); // ligne 0
        Cell cell1 = row.createCell(0); // colonne 0
        Cell cell2 = row.createCell(1); // colonne 1
        Cell cell3 = row.createCell(2); // colonne 2
        Cell cell4 = row.createCell(3); // colonne 3
        Cell cell5 = row.createCell(4); // colonne 4
        Cell cell6 = row.createCell(5); // colonne 5
        Cell cell7 = row.createCell(6); // colonne 6
        Cell cell8 = row.createCell(7); // colonne 7
        Cell cell9 = row.createCell(8); // colonne 8
        
        cell1.setCellValue("Ad      ");
        cell2.setCellValue("Soyad    ");
        cell3.setCellValue("Telefon    ");
        cell4.setCellValue("Durum     ");
        cell5.setCellValue("Kan Grupu  ");
        cell6.setCellValue("Il         ");
        cell7.setCellValue("Ilce      ");
        cell8.setCellValue("Adress     ");
        cell9.setCellValue("Ilgi     ");
        
        Row row2 = sheet.getRow(i);      //sheet.getRow(i) : Cette méthode retourne la ligne à l'index i si elle existe ; sinon, elle retourne null
        while(row2!=null){
            i=i+1;
            row2 = sheet.getRow(i);
        }
        Row row1=  sheet.createRow(i); 
        cell1 = row1.createCell(0); // colonne 0
        cell2 = row1.createCell(1); // colonne 1
        cell3 = row1.createCell(2); // colonne 2
        cell4 = row1.createCell(3); // colonne 3
        cell5 = row1.createCell(4); // colonne 4
        cell6 = row1.createCell(5); // colonne 5
        cell7 = row1.createCell(6); // colonne 6
        cell8 = row1.createCell(7); // colonne 7
        cell9 = row1.createCell(8); // colonne 8
        
        cell1.setCellValue(Ad);
        cell2.setCellValue(Soyad);
        cell3.setCellValue(Telefon);
        cell4.setCellValue(Durum);
        cell5.setCellValue(KanGrupu);
        cell6.setCellValue(Il);
        cell7.setCellValue(Ilce);
        cell8.setCellValue(Adress);
        cell9.setCellValue(Ilgialani);
        i=i+1;
        
        sheet.autoSizeColumn(0);       //permet d'adapter la cellule en fonction de la donne qu'elle recoit
        sheet.autoSizeColumn(1);
        sheet.autoSizeColumn(2);
        sheet.autoSizeColumn(3);
        sheet.autoSizeColumn(4);
        sheet.autoSizeColumn(5);
        sheet.autoSizeColumn(6);
        sheet.autoSizeColumn(7);
        sheet.autoSizeColumn(8);
        
        FileOutputStream fos = new FileOutputStream(file);
        workbook.write(fos);
        workbook.close();
        System.out.println("Fichier Excel créé avec succès.");
        
        
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
        
        /*Workbook workbook = new XSSFWorkbook(); // Créer un nouveau fichier Excel
        Sheet sheet = workbook.createSheet("Feuille1");

        // Écrire une ligne
        Row row = sheet.createRow(0); // ligne 0
        Cell cell1 = row.createCell(0); // colonne 0
        Cell cell2 = row.createCell(1); // colonne 1
        Cell cell3 = row.createCell(2); // colonne 2
        Cell cell4 = row.createCell(3); // colonne 3
        Cell cell5 = row.createCell(4); // colonne 4
        Cell cell6 = row.createCell(5); // colonne 5
        Cell cell7 = row.createCell(6); // colonne 6
        Cell cell8 = row.createCell(7); // colonne 7
        Cell cell9 = row.createCell(8); // colonne 8
        
        cell1.setCellValue("Ad      ");
        cell2.setCellValue("Soyad    ");
        cell3.setCellValue("Telefon    ");
        cell4.setCellValue("Durum     ");
        cell5.setCellValue("Kan Grupu  ");
        cell6.setCellValue("Il         ");
        cell7.setCellValue("Ilce      ");
        cell8.setCellValue("Adress     ");
        cell9.setCellValue("Ilgi     ");
        
        
        
        /*Row row1=  sheet.createRow(1); // ligne 1
        cell1 = row1.createCell(0); // colonne 0
        cell2 = row1.createCell(1); // colonne 1
        cell3 = row1.createCell(2); // colonne 2
        cell4 = row1.createCell(3); // colonne 3
        cell5 = row1.createCell(4); // colonne 4
        cell6 = row1.createCell(5); // colonne 5
        cell7 = row1.createCell(6); // colonne 6
        cell8 = row1.createCell(7); // colonne 7
        
        cell1.setCellValue("Ali      ");
        cell2.setCellValue("Grand    ");
        cell3.setCellValue("calisiyor    ");
        cell4.setCellValue("AB Rh+  ");
        cell5.setCellValue("Konya         ");
        cell6.setCellValue("Selcuk     ");
        cell7.setCellValue("Horozluhan    ");
        cell8.setCellValue("Dance ve muzik    ");*/
        
        /*Row row1=  sheet.createRow(i); // ligne 1
        cell1 = row1.createCell(0); // colonne 0
        cell2 = row1.createCell(1); // colonne 1
        cell3 = row1.createCell(2); // colonne 2
        cell4 = row1.createCell(3); // colonne 3
        cell5 = row1.createCell(4); // colonne 4
        cell6 = row1.createCell(5); // colonne 5
        cell7 = row1.createCell(6); // colonne 6
        cell8 = row1.createCell(7); // colonne 7
        cell9 = row1.createCell(8); // colonne 8
        
        cell1.setCellValue(Ad);
        cell2.setCellValue(Soyad);
        cell3.setCellValue(Telefon);
        cell4.setCellValue(Durum);
        cell5.setCellValue(KanGrupu);
        cell6.setCellValue(Il);
        cell7.setCellValue(Ilce);
        cell8.setCellValue(Adress);
        cell9.setCellValue(Ilgialani);
        i=i+1;
        
        sheet.autoSizeColumn(0);       //permet d'adapter la cellule en fonction de la donne qu'elle recoit
        sheet.autoSizeColumn(1);
        sheet.autoSizeColumn(2);
        sheet.autoSizeColumn(3);
        sheet.autoSizeColumn(4);
        sheet.autoSizeColumn(5);
        sheet.autoSizeColumn(6);
        sheet.autoSizeColumn(7);
        sheet.autoSizeColumn(8);
        

        // Enregistrer le fichier
        try (FileOutputStream fos = new FileOutputStream("Donnees.xlsx",true)) {
            workbook.write(fos);
            workbook.close();
            System.out.println("Fichier Excel créé avec succès.");
        } catch (IOException e) {
            e.printStackTrace();
        }*/
        try{
            FileOutputStream fos = new FileOutputStream("Veir.txt",true);
            OutputStreamWriter wr=new OutputStreamWriter(fos,Charset.forName("ISO-8859-9"));
            BufferedWriter bw =new BufferedWriter(wr);
            String line=Ad+" "+Soyad+" "+Telefon+" "+Durum+" "+KanGrupu+" "+Il+" "+Ilce+" "+Adress+" "+Ilgialani;
            bw.write(line);
            bw.newLine();
            bw.close(); 
            System.out.println("Fichier Excel créé avec succès.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ilgialani=jList1.getSelectedValue();
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jFileChooser1.setCurrentDirectory(new File("C:\\Users\\PC\\Desktop\\github1\\Java-Semestre2\\SystenEnregistre"));
        if(jFileChooser1.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            try {
                FileWriter fw =new FileWriter(jFileChooser1.getSelectedFile().getAbsolutePath(),false);
                BufferedWriter bw =new BufferedWriter(fw);
                bw.write("Ad//"+jTextField1.getText()+"\n");
                bw.newLine();
                bw.write("Soyad//"+jTextField2.getText()+"\n");        
                bw.newLine();
                bw.write("Telefon//"+jFormattedTextField1.getText()+"\n");
                bw.newLine();
                bw.write("Adress//"+jTextArea1.getText().replace("\n", "\t")+"\n");
                bw.newLine();
                String Kangrubu="";
                if(jCheckBox1.isSelected()){
                    Kangrubu="A";
                }
                if(jCheckBox2.isSelected()){
                    Kangrubu= Kangrubu+"B";
                }
                if(jCheckBox3.isSelected()){
                    Kangrubu="AB";
                }
                if(jCheckBox4.isSelected()){
                    Kangrubu= "O";
                }
                if(jCheckBox5.isSelected()){
                    Kangrubu= Kangrubu+" Rh+";
                }
                if(jCheckBox6.isSelected()){
                    Kangrubu= Kangrubu+" Rh-";
                }
                bw.write("Kan Grubu//"+Kangrubu+"\n");
                bw.newLine();
                int seciler[];
                seciler=jList1.getSelectedIndices();
                String secil="";
                for(int i=0;i<seciler.length;i++){
                    secil+=seciler[i]+"//";
                }
                bw.write("Ilgi//"+secil+"\n");
                bw.newLine();
                if(jRadioButton1.isSelected()){
                    bw.write("Durum//1\n");
                    bw.newLine();
                }
                if(jRadioButton2.isSelected()){
                    bw.write("Durum//2\n");
                    bw.newLine();
                }
                bw.write("Il//"+jComboBox1.getSelectedIndex()+"\n");
                bw.newLine();
                bw.write("Ilce//"+jComboBox2.getSelectedIndex()+"\n");
                bw.newLine();
                bw.close();
                JOptionPane.showMessageDialog(this, "Kayit basari gerceklestir!!!!", "Kayit", JOptionPane.INFORMATION_MESSAGE);
                
                //reinitialisation de la fiche d'enreigistrement
                jTextField1.setText("");
                jTextField2.setText("");
                jFormattedTextField1.setText("");
                jTextArea1.setText("");
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
                buttonGroup2.clearSelection();  //permet de deselectionner les selections des jboutton
                buttonGroup1.clearSelection();  //permet de deselectionner les selections des jboutton
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
            } catch (IOException ex) {
                Logger.getLogger(fenetre1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jFileChooser1.setCurrentDirectory(new File("C:\\Users\\PC\\Desktop\\github1\\Java-Semestre2\\SystenEnregistre"));
        if(jFileChooser1.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            try {
                FileReader fr =new FileReader(jFileChooser1.getSelectedFile().getAbsolutePath());
                BufferedReader br =new BufferedReader(fr);
                String line =br.readLine();
                while(line!=null){
                    String[] parca=line.split("//");
                    
                    switch(parca[0]){
                        case "Ad":
                            jTextField1.setText(parca[1]);
                            break;
                        case "Soyad":
                            jTextField2.setText(parca[1]);
                            break;
                        case "Telefon":
                            jFormattedTextField1.setText(parca[1]);
                            break;
                        case "Adress":
                            jTextArea1.setText(parca[1].replace("\t", "\n"));
                            break;
                        case "Kan Grubu":
                            if(parca[1].contains("A")){
                                jCheckBox1.setSelected(true);
                            }
                            if(parca[1].contains("B")){
                                jCheckBox2.setSelected(true);
                            }
                            if(parca[1].contains("O")){
                                jCheckBox4.setSelected(true);
                            }
                            if(parca[1].contains("AB")){
                                jCheckBox3.setSelected(true);
                            }
                            if(parca[1].contains("Rh+")){
                                jCheckBox5.setSelected(true);
                            }
                            if(parca[1].contains("Rh-")){
                                jCheckBox6.setSelected(true);
                            }
                            break;
                        case "Ilgi":
                            int seciler[]= new int[parca.length-1];
                            for(int i = 1; i < parca.length; i++)
                                seciler[i-1] = Integer.parseInt(parca[i]);
                            jList1.setSelectedIndices(seciler);
                            break;
                        case "Durum":
                            if (parca[1].equals("1")){
                              jRadioButton1.setSelected(true);
                            }  
                            else
                                jRadioButton2.setSelected(true);
                            break;
                        case "Il":
                            jComboBox1.setSelectedIndex(Integer.parseInt(parca[1]));
                            break;
                        case "Ilce":
                            jComboBox2.setSelectedIndex(Integer.parseInt(parca[1]));
                            break;    
                    }
                    line =br.readLine();
                    
                }
                br.close();
                
            } catch (IOException ex) {
                Logger.getLogger(fenetre1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void kaydet(){
        Ad=jTextField1.getText();
        Soyad=jTextField2.getText();
        Telefon=jFormattedTextField1.getText();
        Adress=jTextArea1.getText();
        Il=jComboBox1.getSelectedItem().toString();
        Ilce=jComboBox2.getSelectedItem().toString();
        if(jRadioButton1.isSelected()){
            Durum="Ogrenci";
        }
        if(jRadioButton2.isSelected()){
            Durum="Calisiyor";
        }
        if(jCheckBox1.isSelected()){
            KanGrupu="A";
        }
        if(jCheckBox2.isSelected()){
            KanGrupu=KanGrupu+"B";
        }
        if(jCheckBox3.isSelected()){
            KanGrupu="AB";
        }
        if(jCheckBox4.isSelected()){
            KanGrupu="O";
        }
        if(jCheckBox5.isSelected()){
            KanGrupu=KanGrupu+"Rh+";
        }
        if(jCheckBox6.isSelected()){
            KanGrupu=KanGrupu+"Rh-";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetre1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetre1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetre1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetre1().setVisible(true);
            }
        });
    }
    
    int i=1;
    String Ad,Soyad,Telefon,Adress,Il,Ilce,Durum,KanGrupu,Ilgialani;
    public String[] iller;
    Vector<Integer> ilkodlari;
    public javax.swing.DefaultComboBoxModel ilmodel;
    public javax.swing.DefaultComboBoxModel[] ilceler;
    public javax.swing.DefaultListModel ilgi;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
